# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [6]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(1,6)
arr_2 = np.arange(5)
arr_2

array([0, 1, 2, 3, 4])

In [8]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

In [9]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [11]:
# Checking the dimensions of the array
arr_3.ndim

2

In [12]:
# Printing the created array
arr_3

array([[1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4]])

In [13]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [14]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = np.reshape(arr_4,(5,2))

In [16]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape((5,4))

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [20]:
# Stacking arr_5 and arr_6
np.hstack(arr_5,arr_6)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [21]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [24]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = np.reshape(arr_6,(10,2))
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [25]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [28]:
a = np.array([[7, 13, 14],
              [18, 10, 17],
              [11, 12, 19]])
b = np.array([16, 6, 1])
c = np.array([[5, 8, 4, 3]])

In [46]:
np.transpose(np.vstack((np.transpose(np.vstack((a,b))),c)))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [48]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [49]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])